export const UPDATE_RECIPES = 'UPDATE_RECIPES';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SHOPPING_LIST = 'UPDATE_SHOPPING_LIST';
export const UPDATE_WEEKPLAN = 'UPDATE_WEEKPLAN';
