export const UPDATE_RECIPES = 'UPDATE_RECIPES';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SHOPPING_LIST = 'UPDATE_SHOPPING_LIST';
export const UPDATE_WEEKPLAN = 'UPDATE_WEEKPLAN';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';
export const CLEAR_REMOVED_LIST_ITEMS = 'CLEAR_REMOVED_LIST_ITEMS';
